# Generated by Django 4.0.6 on 2022-07-20 01:04

from django.db import migrations


def create_default_games(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    Game.objects.create(
        name='Brawlhalla',
        description='Brawlhalla é um jogo de luta free-to-play desenvolvido pela Blue Mammoth Games e publicado pela Ubisoft para macOS, Microsoft Windows, PlayStation 4, PlayStation 5, Nintendo Switch, Xbox One, Xbox Series S & X, Android e iOS, com cross completo - jogue em todas as plataformas.',
        price=59.90,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_games),
    ]