# Generated by Django 4.0.6 on 2022-07-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_default_developers'),
        ('platforms', '0002_default_platforms'),
        ('games', '0003_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, db_column='developer_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='developers.developer'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='platforms.platform'),
        ),
    ]
