# Generated by Django 4.0.6 on 2022-07-20 00:57

from django.db import migrations

def create_default_platforms(apps, schema_editor):
    Platform = apps.get_model('platforms', 'Platform')
    Platform.objects.create(name='Linux')
    Platform.objects.create(name='Macos')
    Platform.objects.create(name='Windows')


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_platforms),
    ]
