# Generated by Django 4.0.6 on 2022-07-20 01:00

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')
    Category.objects.create(name='Role-playing')
    Category.objects.create(name='Fantasy')
    Category.objects.create(name='Adventure')


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]

