# Generated by Django 4.0.6 on 2022-07-20 01:03

from django.db import migrations

def create_default_developers(apps, schema_editor):
    Developer = apps.get_model('developers', 'Developer')
    Developer.objects.create(name='CD Projekt Red')


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_developers),
    ]

